AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Cloudformation to Create Athena PatchSummary Table for SSM'
Parameters:
  SSMDataBaseName:
    Type: "String"
    Description: "Athena Database Name"
    MinLength: "2"
    MaxLength: "31"
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: "Can only contain ASCII characters"
    Default: default
  Environment:
    Type: "String"
    AllowedValues:
      - dev
      - qa
      - prod
    Description: "Which Environment?"
Resources:
  AthenaNamedQuery:
    Type: AWS::Athena::NamedQuery
    Properties:
      Database: !Ref SSMDataBaseName
      Description: "Create the AWS_PatchSummary table"
      Name: "CreatePatchSummary"
      QueryString:
        Fn::Sub:
          - |
                    CREATE EXTERNAL TABLE IF NOT EXISTS ${SSMDataBaseName}.AWS_PatchSummary (
                      `ResourceId` string,
                      `PatchGroup` string,
                      `BaselineId` string,
                      `SnapshotId` string,
                      `OwnerInformation` string,
                      `InstalledCount` int,
                      `InstalledOtherCount` int,
                      `NotApplicableCount` int,
                      `MissingCount` int,
                      `FailedCount` int,
                      `OperationType` string,
                      `OperationStartTime` string,
                      `OperationEndTime` string
                    )
                    PARTITIONED BY (AccountId string, Region string, ResourceType string)
                    ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
                    WITH SERDEPROPERTIES (
                      'serialization.format' = '1'
                    ) LOCATION 's3://${S3Bucket}/AWS:PatchSummary/'
          - S3Bucket:
              Fn::ImportValue:
                Fn::Sub: "SSMS3Bucket${Environment}"
  PatchSummaryTableFixQuery:
    Type: AWS::Athena::NamedQuery
    Properties:
      Database: !Ref SSMDataBaseName
      Description: "Fix PatchSummary Table"
      Name: "FixPatchSummaryTable"
      QueryString: !Sub |
                    MSCK REPAIR TABLE ${SSMDataBaseName}.AWS_PatchSummary
Outputs:
  SSMAthenaApplicationTable:
    Value: !Ref AthenaNamedQuery
    Description: "Named query for creating the AWS_PatchSummary Table"
    Export:
      Name: !Sub SSMAthena-PatchSummaryTable-${Environment}
