AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Cloudformation to Create Athena Tables for SSM'
Parameters:
  SSMDataBaseName:
    Type: "String"
    Description: "Athena Database Name"
    MinLength: "2"
    MaxLength: "31"
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: "Can only contain ASCII characters"
    Default: default
  Environment:
    Type: "String"
    AllowedValues:
      - dev
      - qa
      - prod
    Description: "Which Environment?"
  S3Bucket:
    Type: "String"
    Description: "S3Bucket to use"
    Default: "SSM-S3Bucket-dev"
Resources:
  AthenaNamedQuery:
    Type: AWS::Athena::NamedQuery
    Properties:
      Database: !Ref SSMDataBaseName
      Description: "Create the AWS_Application table"
      Name: "CreateApplicationTable"
      QueryString: !Sub |
                  CREATE EXTERNAL TABLE IF NOT EXISTS ${SSMDataBaseName}.AWS_Application (
                      "ResourceId" string,
                      "Name" string,
                      "ApplicationType" string,
                      "Publisher" string,
                      "Version" string,
                      "InstalledTime" string,
                      "Architecture" string,
                      "URL" string
                    )
                    PARTITIONED BY (AccountId string, Region string, ResourceType string)
                    ROW FORMAT SERDE "org.openx.data.jsonserde.JsonSerDe"
                    WITH SERDEPROPERTIES (
                      "serialization.format" = "1"
                    ) LOCATION "s3://${S3Bucket}/AWS:Application/"

                    MSCK REPAIR TABLE ${SSMDataBaseName}.AWS_Application

Outputs:
  SSMAthenaApplicationTable:
    Value: !Ref AthenaNamedQuery
    Description: "Named query for creating the AWS_Appliation Table"
    Export: !Sub SSMAthenaApplicationTable-${Environment}
